### PR TITLE
Quick fix for Django 1.11 compatibility

### PR DESCRIPTION
**Pull request by webtweakers**
A change in Django 1.11 -- the location of flatatt -- makes django-tinymce4-widget incompatible. This quick fix seems to fix that.

### CODE REVIEW

**Comment by browniebroke** [comment]
Thanks a lot for the contribution! Much appreciated!

**Comment by webtweakers** [comment]
You're welcome. Could you possibly bump the version number and push this to pypi?
Your version of django-tinymce4 is the best out there and I love using it! :) And it would be great if the pypi package index stays up to date.

**Comment by browniebroke** [comment]
Wow, I had no idea someone else was using it. Thanks for the nice comment, but I mostly modified another fork. I didn't write the whole thing. 

I'm on vacation now, and I wanted to update the build matrix and pypi classifiers before doing the release, I realise they are quite outdated. I'll open an issue, if you fancy picking it up?

**Comment by webtweakers** [comment]
Ok, I updated the build matrix and pypi classifiers plus some other things, including some fixes from https://github.com/romanvm/django-tinymce4-lite.

And yes, I've been searching for a clean implementation of django + tinymce4 and was about to embark on implementing it myself when I found your fork. Nicely done!

**Pull request merged**
